---
workspace:
  SIZE: !!int 3
  LIMIT_X:
    - !!float 0.2
    - !!float 0.65
  LIMIT_Y:
    - !!float -0.28
    - !!float 0.28
  LIMIT_Z:
    - !!float 0.03
    - !!float 0.6


positions:
  robot_home_q: 
    - !!float 0.0003
    - !!float -0.7845
    - !!float -0.0003
    - !!float -2.3569
    - !!float 0.0006
    - !!float 1.5713
    - !!float 0.7858


         
